# Generated by Django 5.0.2 on 2024-03-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recepit',
            new_name='Recepie',
        ),
    ]
