# Generated by Django 5.0.2 on 2024-03-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_rename_recepit_recepie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recepie',
            new_name='Recipe',
        ),
    ]
